name: My First Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.9  # Python 環境をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Python のバージョンを指定
      - name: Display Python version
        run: python --version  # Python のバージョンを表示